name: movie_app
description: "Offline Cache using the Decorator Design Pattern"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  either_dart: ^1.0.0
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  oktoast: ^3.4.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  modal_progress_hud_nsn: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
